profiles: 本地环境(local)
spring:
  redis:
      database: 0
      host: 192.168.88.59
      port: 6379
      timeout: 1000
      lettuce:
        pool:
           max-active: 8
           max-wait: -1
           max-idle: 8
           min-idle: 0
  rocketmq:
     producer:
       group: quality-control-group
     nameServer: 192.168.88.59:9876
swagger:
   enable: true
queue:
    topic: testTopic
    consumerGroup: quality-consumer-group
